### ISSUE TITLE
Removing watch/unwatch classes from the browser core breaks L4E

### ISSUE THREAD

**Issue by JustOff** [JustOff/L4E#1]
After watch/unwatch classes removal in [UXP#1257](https://github.com/MoonchildProductions/UXP/issues/1257), L4E does not work properly.

To fix this, we need to implement something like what was done in [UXP#1261](https://github.com/MoonchildProductions/UXP/issues/1261).

**Comment by JustOff** [comment]
> considering we're not using it as an extension, we don't need the bit for regenerating bindings in case `XULBrowserWindow` would be changed because that never happens with it being part of the browser chrome itself; this allows us to skip the check and handler on the (otherwise nonconfigurable) `XULBrowserWindow` which would otherwise be a snag because you can't `defineProperty` on something nonconfigurable.

I wish I could say I fully understand the above, but unfortunately this is not true.

@wolfbeast, could you please explain your reasoning a little more and advise how best to proceed in the case of the extension?

**Comment by wolfbeast** [comment]
The reasoning is that XULBrowserWindow should never change when all the code is part of the window object.
Even as an extension that might be loaded/unloaded on demand, I'm not sure if you'd ever lose the XULBrowserWindow from the window object; even if so, I'm guessing you'd still initialize everything fresh when loading, anyway, so I'm not entirely sure what specific scenario that code is supposed to address.

I'd say: just try it without (i.e. remove/comment out https://github.com/JustOff/L4E/blob/495ea11f03933d93e4a48b5f24000293af537dc5/modules/Status.jsm#L148-L161 and see what happens in case of extension use?) :)

**Comment by Vangelis66** [comment]
I am running the latest PM unstable win32 build (v**28.8.0a1**, buildID=**20191104092159**) on Win7SP1 64-bit, with latest L4E v**1.0.5** installed; the only two perceivable breakages in my setup are: 
1. I have a progress bar displayed in the bottom of the Location Bar; my colour choice for that bar is `#3366FF`; the progress bar is now still displayed as intended (in the bottom), but always in **grey** (so, custom colour choice ignored) ...
2. I have a second progress bar displayed in the Status Bar itself, placed towards the left, before other extension icons; the "inside" of that progress bar is a part of a static image on my disk: 
`#3366FF url("file:///D:/path_to/image.png") no-repeat left center`; that second progress bar is now always displayed in a bright **green** colour (so, custom settings ignored) ...

_However_, I am happy to report that the "fix" suggested by @wolfbeast in the comment above appears **to have cured both these issues** for me 👍 😄 

Best regards.

**Comment by JustOff** [comment]
@wolfbeast, thanks, given that `XULBrowserWindow.watch/unwatch` is [already provided](https://github.com/MoonchildProductions/UXP/commit/ff881bdb6795e0f307b93919f98f454bedde4bb6#diff-7ef94f0b1715829e60a7f75492a91a4bR124-R172) by the browser module, `_window.watch` is only thing the extension should [take care of](https://github.com/JustOff/L4E/commit/32f438cf0b30f032b656b59fcaeab4116353b107).
