### ISSUE TITLE
Just emailed you inviting your collaboration

### ISSUE THREAD

**Issue by clifford269** [JustOff/L4E#2]

**Comment by rebop** [comment]
What am I missing???????

**Comment by clifford269** [comment]
> What am I missing???????

what, are you a dev?

**Comment by rebop** [comment]
I got an email that had a link to here today. No idea why or what it means. I am not a developer. I do do Beta Testing.

**Comment by clifford269** [comment]
I didn't email you then.

**Comment by rebop** [comment]
Sure. I imagined it.

**Comment by clifford269** [comment]
Hehe, so you ARE the JustOff guy himself? If not, I don't know how it got to you LOL.
